[package]
name = "simple_math"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[features]
default = ["fmt"]
fmt = []

[profile.release]
opt-level = 3
lto = true
